# mdbook-pdf の設定を追加すると mdbook build 実行時に毎回 PDF が生成されてしまう
# それを避けるために、このファイルに設定内容を避難させている
[output.html.print]
enable = true

[output.pdf]
theme = "light"
display-header-footer = false
print-background = true
margin-top = 0.5
margin-bottom = 0.5
margin-left = 0.0
margin-right = 0.0
scale = 0.8
prefer-css-page-size = true
