[book]
authors = ["Seasawher"]
language = "ja"
multilingual = false
src = "src"
title = "Lean by Example"
description = "プログラミング言語であるとともに定理証明支援系でもある Lean 言語と、その主要なライブラリの使い方を豊富なコード例とともに解説した資料です。"

[build]
create-missing = false
build-dir = "book"

[output.html]
additional-js = ["assets/blockPlay.js", "assets/filePlay.js", "assets/fzf.umd.js", "assets/elasticlunr.js"]
no-section-label = true
git-repository-url = "https://github.com/lean-ja/lean-by-example"
edit-url-template = "https://raw.githubusercontent.com/lean-ja/lean-by-example/main/{path}"
default-theme = "ayu"
site-url = "https://lean-ja.github.io/lean-by-example/"

[output.html.fold]
enable = true
level = 2

[output.html.print]
enable = true

[output.pdf]
theme = "light"
display-header-footer = false
print-background = true
margin-top = 0.5
margin-bottom = 0.5
margin-left = 0.0
margin-right = 0.0
scale = 0.8
prefer-css-page-size = true
