[book]
authors = ["Seasawher"]
language = "ja"
multilingual = false
src = "src"
title = "Lean4 タクティク逆引きリスト"
description = "「普段の数学を Lean でどう実現するのか」という疑問にお答えするための，タクティク逆引きリストです."

[build]
create-missing = false
build-dir = "book"

[output.html]
additional-js = ["assets/blockPlay.js", "assets/filePlay.js", "assets/fzf.umd.js", "assets/elasticlunr.js"]
no-section-label = true
git-repository-url = "https://github.com/lean-ja/tactic-cheatsheet"
edit-url-template = "https://raw.githubusercontent.com/lean-ja/tactic-cheatsheet/main/{path}"
default-theme = "ayu"

[output.html.fold]
enable = true
level = 0

[output.html.print]
enable = false
