[book]
authors = ["Seasawher"]
language = "ja"
src = "booksrc" # 単に src とすると検索ノイズが多くなることを考慮
title = "Lean by Example"
description = "プログラミング言語であるとともに定理証明支援系でもある Lean 言語と、その主要なライブラリの使い方を豊富なコード例とともに解説した資料です。"

[build]
# ビルドしたファイルを保存するディレクトリ
build-dir = "book"
# ビルド実行時に勝手にファイルを作らない
create-missing = false

[output.html]
additional-js = [
  # コードブロックごとに実行ボタンを表示する
  "assets/blockPlay.js",
  # ページごとに実行ボタンを表示する
  "assets/filePlay.js",
  # 検索機能を改善し、日本語で検索できるようにする
  "assets/fzf.umd.js", "assets/elasticlunr.js",
  # サイドバーに目次を表示する
  "assets/pagetoc.js",
  # 見出しをMathlhib4Helpへの外部リンクに変換する
  "assets/replaceToLink.js",
  # ランダムページボタンを表示する
  "assets/randomPage.js"
]
additional-css = [
  # mdbook-admonish のスタイル
  "./assets/mdbook-admonish.css",
  # サイドバーに目次を表示する
  "./assets/pagetoc.css"
]

# セクション番号を振らない
no-section-label = true

# git リポジトリへのリンクを表示する
git-repository-url = "https://github.com/lean-ja/lean-by-example"

# 編集ボタンを上書きして、コード実行ボタンにするための設定
edit-url-template = "https://raw.githubusercontent.com/lean-ja/lean-by-example/main/{path}"

# 404 ページが正常にはたらくようにするために必要
site-url = "https://lean-ja.github.io/lean-by-example/"

# ayu テーマをデフォルトにする
# Rust テーマでは admonish のスタイルが変になるため
default-theme = "ayu"

[output.html.search]
# 検索したときに、クエリと見出し語が一致していれば見出し語のページがトップに出てくるようにする
boost-title = 25

[output.html.fold]
# 目次の折りたたみの設定
enable = true
level = 0

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.2" # do not edit: managed by `mdbook-admonish install`
