name: 新規項目・追記リクエスト
description: 追加してほしい項目や題材をリクエストします。
title: "リクエスト: <title>"
body:
- type: textarea
  attributes:
    label: 概要
    description: 追加してほしい内容を記入してください。

- type: textarea
  attributes:
    label: 備考
    description: 参考資料やコード例があれば記入してください。
