name: auto merge PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    # 自分が作成したPRでのみ有効化する
    if: ${{ github.actor == 'Seasawher' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Merge PR
        run: |
          gh pr merge --merge --auto
