# see: https://github.com/rami3l/plfl/blob/master/.github/workflows/ci.yml
name: CI

# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: lean action
        uses: leanprover/lean-action@v1-beta
        with:
          build-args: "--quiet"
          test: false

  windows_build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install elan
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1
          echo 1 | powershell -ExecutionPolicy Bypass -f elan-init.ps1
          del elan-init.ps1
        shell: pwsh

      - name: add elan to PATH
        run: (Resolve-Path ~/.elan/bin).Path >> $Env:GITHUB_PATH
        shell: pwsh

      - name: get mathlib cache
        run: lake exe cache get
        shell: pwsh

      - name: run lake build
        run: lake build --quiet
        shell: pwsh
